[package]
name = "interlib"
version = "0.1.0"
edition = "2024"

[lib]
name = "interlib"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
numpy = "0.27"
ndarray = "0.16"
rayon = "1.10"